In [357]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/train/Train.xlsx
/kaggle/input/testt/Test.xlsx


In [358]:
import pandas as pd
import numpy as np


In [359]:
df = pd.read_excel('/kaggle/input/train/Train.xlsx', index_col=0) 

df

Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  ...  Q69  Q70  Q71  Q72  Q73  \
NO                                            ...                            
11    1   5   2   5   1   3   1   1   1    2  ...    4    3    1    4    1   
12    2   5   1   5   1   5   1   1   1    2  ...    5    3    1    5    1   
13    2   4   2   5   2   5   2   2   2    2  ...    4    3    2    3    2   
14    2   5   1   5   2   5   2   1   2    2  ...    3    2    2    4    2   
15    1   4   1   5   1   3   1   1   1    1  ...    4    2    2    3    1   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
297   3   4   3   5   4   5   2   2   2    2  ...    5    1    3    4    1   
298   3   4   3   5   2   3   3   1   2    3  ...    2    3    4    3    3   
299   2   4   3   3   2   4   2   1   1    3  ...    5    4    2    4    2   
300   4   4   1   5   3   2   2   2   2    4  ...    4    3    3    4    3   
301   2   4   3   4   3   4   2   2   2    4  ...    4    2    2    4    2   

     Q74  Q75  Q76  Q77  CLASS  
NO                              
11     2    2    3    4      1  
12     2    1    3    1      1  
13     3    2    2    4      1  
14     2    4    3    4      1  
15     3    1    3    5      1  
..   ...  ...  ...  ...    ...  
297    3    4    4    4      3  
298    3    4    3    3      3  
299    3    3    3    4      3  
300    3    4    4    4      3  
301    2    4    4    4      3  

[281 rows x 78 columns]

In [360]:
df.columns

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11',
       'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21',
       'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30', 'Q31',
       'Q32', 'Q33', 'Q34', 'Q35', 'Q36', 'Q37', 'Q38', 'Q39', 'Q40', 'Q41',
       'Q42', 'Q43', 'Q44', 'Q45', 'Q46', 'Q47', 'Q48', 'Q49', 'Q50', 'Q51',
       'Q52', 'Q53', 'Q54', 'Q55', 'Q56', 'Q57', 'Q58', 'Q59', 'Q60', 'Q61',
       'Q62', 'Q63', 'Q64', 'Q65', 'Q66', 'Q67', 'Q68', 'Q69', 'Q70', 'Q71',
       'Q72', 'Q73', 'Q74', 'Q75', 'Q76', 'Q77', 'CLASS'],
      dtype='object')

In [361]:
df.isnull().any()

Q1       False
Q2       False
Q3       False
Q4       False
Q5       False
         ...  
Q74      False
Q75      False
Q76      False
Q77      False
CLASS    False
Length: 78, dtype: bool

In [362]:
df_new = df
df_new['Q1'] = pd.factorize(df_new['Q1'])[0]
df_new['Q2'] = pd.factorize(df_new['Q2'])[0]
df_new.dtypes

Q1       int64
Q2       int64
Q3       int64
Q4       int64
Q5       int64
         ...  
Q74      int64
Q75      int64
Q76      int64
Q77      int64
CLASS    int64
Length: 78, dtype: object

In [363]:
df

Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  ...  Q69  Q70  Q71  Q72  Q73  \
NO                                            ...                            
11    0   0   2   5   1   3   1   1   1    2  ...    4    3    1    4    1   
12    1   0   1   5   1   5   1   1   1    2  ...    5    3    1    5    1   
13    1   1   2   5   2   5   2   2   2    2  ...    4    3    2    3    2   
14    1   0   1   5   2   5   2   1   2    2  ...    3    2    2    4    2   
15    0   1   1   5   1   3   1   1   1    1  ...    4    2    2    3    1   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
297   2   1   3   5   4   5   2   2   2    2  ...    5    1    3    4    1   
298   2   1   3   5   2   3   3   1   2    3  ...    2    3    4    3    3   
299   1   1   3   3   2   4   2   1   1    3  ...    5    4    2    4    2   
300   3   1   1   5   3   2   2   2   2    4  ...    4    3    3    4    3   
301   1   1   3   4   3   4   2   2   2    4  ...    4    2    2    4    2   

     Q74  Q75  Q76  Q77  CLASS  
NO                              
11     2    2    3    4      1  
12     2    1    3    1      1  
13     3    2    2    4      1  
14     2    4    3    4      1  
15     3    1    3    5      1  
..   ...  ...  ...  ...    ...  
297    3    4    4    4      3  
298    3    4    3    3      3  
299    3    3    3    4      3  
300    3    4    4    4      3  
301    2    4    4    4      3  

[281 rows x 78 columns]

In [364]:
df_new['CLASS'] = pd.factorize(df_new['CLASS'])[0]

In [365]:
df_new

Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  ...  Q69  Q70  Q71  Q72  Q73  \
NO                                            ...                            
11    0   0   2   5   1   3   1   1   1    2  ...    4    3    1    4    1   
12    1   0   1   5   1   5   1   1   1    2  ...    5    3    1    5    1   
13    1   1   2   5   2   5   2   2   2    2  ...    4    3    2    3    2   
14    1   0   1   5   2   5   2   1   2    2  ...    3    2    2    4    2   
15    0   1   1   5   1   3   1   1   1    1  ...    4    2    2    3    1   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
297   2   1   3   5   4   5   2   2   2    2  ...    5    1    3    4    1   
298   2   1   3   5   2   3   3   1   2    3  ...    2    3    4    3    3   
299   1   1   3   3   2   4   2   1   1    3  ...    5    4    2    4    2   
300   3   1   1   5   3   2   2   2   2    4  ...    4    3    3    4    3   
301   1   1   3   4   3   4   2   2   2    4  ...    4    2    2    4    2   

     Q74  Q75  Q76  Q77  CLASS  
NO                              
11     2    2    3    4      0  
12     2    1    3    1      0  
13     3    2    2    4      0  
14     2    4    3    4      0  
15     3    1    3    5      0  
..   ...  ...  ...  ...    ...  
297    3    4    4    4      2  
298    3    4    3    3      2  
299    3    3    3    4      2  
300    3    4    4    4      2  
301    2    4    4    4      2  

[281 rows x 78 columns]

In [366]:
df_new = df_new.dropna(0,'any')
df_new

Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  ...  Q69  Q70  Q71  Q72  Q73  \
NO                                            ...                            
11    0   0   2   5   1   3   1   1   1    2  ...    4    3    1    4    1   
12    1   0   1   5   1   5   1   1   1    2  ...    5    3    1    5    1   
13    1   1   2   5   2   5   2   2   2    2  ...    4    3    2    3    2   
14    1   0   1   5   2   5   2   1   2    2  ...    3    2    2    4    2   
15    0   1   1   5   1   3   1   1   1    1  ...    4    2    2    3    1   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
297   2   1   3   5   4   5   2   2   2    2  ...    5    1    3    4    1   
298   2   1   3   5   2   3   3   1   2    3  ...    2    3    4    3    3   
299   1   1   3   3   2   4   2   1   1    3  ...    5    4    2    4    2   
300   3   1   1   5   3   2   2   2   2    4  ...    4    3    3    4    3   
301   1   1   3   4   3   4   2   2   2    4  ...    4    2    2    4    2   

     Q74  Q75  Q76  Q77  CLASS  
NO                              
11     2    2    3    4      0  
12     2    1    3    1      0  
13     3    2    2    4      0  
14     2    4    3    4      0  
15     3    1    3    5      0  
..   ...  ...  ...  ...    ...  
297    3    4    4    4      2  
298    3    4    3    3      2  
299    3    3    3    4      2  
300    3    4    4    4      2  
301    2    4    4    4      2  

[280 rows x 78 columns]

In [367]:
pel_class = np.unique(df_new['CLASS'])
pel_class

array([0, 1, 2])

In [368]:
pel_value = [sum(df_new['CLASS']==pel_class[0]),
             sum(df_new['CLASS']==pel_class[1]),
            sum(df_new['CLASS']==pel_class[2])]
pel_value

[134, 85, 61]

In [369]:
y = df_new['CLASS'].values
X = df_new.drop(['CLASS'],axis = 1).values

In [370]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=1)
X,y = sm.fit_resample(X,y)

In [371]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.5,random_state=0)

In [372]:
np.shape(X_test)

(41, 77)

In [373]:
np.shape(y_test)

(41,)

In [374]:
np.max(X_train_norm,0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [375]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(X_train)
X_train_norm = scaler.transform(X_train)
X_test_norm = scaler.transform(X_test)

In [376]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
params = {
    'C' : [2,4,6,8,10,12], 
    'gamma' : [0.03125, 0.0625, 0.125, 0.25, 0.5, 1, 2, 4, 8, 16, 32] 
    
}
clf = GridSearchCV(SVC(),params, cv=10)
clf.fit(X_train_norm, y_train)
print("Best params : " + str(clf.best_params_))
print("10CV accuracy : "+str(clf.best_score_*100))

Best params : {'C': 6, 'gamma': 0.125}
10CV accuracy : 93.36336336336336


In [377]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
y_predict = clf.predict(X_test_norm)
print("Test accuracy : "+str(sum(y_test == y_predict)/len(y_test)*100))

Test accuracy : 97.5609756097561


In [378]:
df_t= pd.read_excel('/kaggle/input/testt/Test.xlsx', index_col=0) 

In [379]:
df_t['CLASS'] = pd.factorize(df_t['CLASS'])[0]

In [380]:
yt = df_t['CLASS'].values
Xt = df_t.drop(['CLASS'],axis = 1).values

In [381]:
yt

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [382]:
X_test_norm = scaler.transform(Xt)

In [383]:
y_predict = clf.predict(X_test_norm)
print("Test accuracy : "+str(sum(yt == y_predict)/len(yt)*100))

Test accuracy : 66.66666666666666


In [384]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)


from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(X_train)
X_train_norm = scaler.transform(X_train)
X_test_norm = scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
params = {
    'n_estimators' : [10,50,100],
    'min_samples_leaf' : [1,2,4],
    'max_features' : ['sqrt',0.5,0.8],
}
clf = GridSearchCV(RandomForestClassifier(random_state=0),params, cv = 10)
clf.fit(X_train_norm, y_train)
print("Best params : " + str(clf.best_params_))
print("10CV accuracy : "+str(clf.best_score_*100))

Best params : {'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 100}
10CV accuracy : 86.29734848484848


In [385]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
clf.fit(X_train_norm, y_train)
y_predict = clf.predict(X_test_norm)
print("Test accuracy : "+str(sum(y_test == y_predict)/len(y_test)*100))

Test accuracy : 76.5432098765432


In [386]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
params = {
    'n_estimators' : [10,50,100,200,500],
    'min_samples_leaf' : [1,2,4,8,16,32],
    'max_features' : ['sqrt',0.5,0.8],
    'criterion' : ['gini','entropy']
}
clf = GridSearchCV(RandomForestClassifier(random_state=0),params, cv = 10)
clf.fit(X_train_norm, y_train)
print("Best params : " + str(clf.best_params_))
print("10CV accuracy : "+str(clf.best_score_*100))

KeyboardInterrupt: 