In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[0,0]

1

In [5]:
a[1,:]

array([4, 5, 6])

In [6]:
a[:,-1]

array([3, 6, 9])

In [7]:
a[:,-3
 ]

array([1, 4, 7])

In [8]:
a[-1,:]

array([7, 8, 9])

In [9]:
a[:,1]

array([2, 5, 8])

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

4

In [11]:
np.size(a,0)

4

นับ จำนวน row


In [12]:
np.size(a,1)

3

นับ จำนวน colum


In [13]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [14]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

In [15]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [16]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [17]:
b = np.full
b

<function numpy.full(shape, fill_value, dtype=None, order='C')>

In [18]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

matrix เอกลักษณ์

In [19]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [20]:
np.empty([5,5])

array([[4.65776928e-310, 8.15208316e-322, 9.29654051e+242,
        4.39324667e+228, 5.37988202e+228],
       [1.38795503e+219, 2.86749934e+161, 5.95144714e+228,
        1.99886516e+161, 1.09313427e+189],
       [3.31602997e-080, 2.16063140e+233, 8.48254144e+175,
        2.99688141e-080, 1.43769634e-023],
       [3.23225296e-295, 1.24571164e+137, 6.51686540e+256,
        9.98390183e+164, 3.89570063e+034],
       [7.38255668e+015, 6.46676985e+256, 5.03211681e-071,
        3.28175647e-028, 5.05060978e+223]])

In [21]:
np.random.rand()

0.6336659790115347

In [22]:
np.random.randint(5)

2

In [23]:
np.random.seed(2)
np.random.randint(2,5)


2

seed คือ รูปแบบ  lock ผล


In [24]:
np.round(np.random.rand(5,5)*1000)

array([[185., 932., 948., 485., 321.],
       [154., 699., 120., 485., 633.],
       [818., 683., 499., 587., 720.],
       [258., 546., 407., 177., 970.],
       [297., 288., 116., 182., 494.]])

มีารปัด


In [25]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([3, 5, 2, 8, 9])

In [26]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([ 6,  5,  4,  7, 10])

ไม่เอาตัวซ้ำ

In [27]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose


array([[0.14856478, 0.85228103, 0.50952588, 0.21726993, 0.99326629],
       [0.14856478, 0.85228103, 0.50952588, 0.21726993, 0.99326629],
       [0.51513912, 0.22099815, 0.74663141, 0.43153777, 0.88830375]])

เอามา 3 แถว

In [28]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix


array([[ 5,  0,  8,  6, 10],
       [ 5,  1, 10,  7,  4],
       [ 3,  6,  1,  4, 10],
       [ 0,  8, 10,  5,  4],
       [ 2,  9,  7,  1,  9]])

In [29]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 1, 2, 0, 1],
       [0, 0, 2, 1, 2],
       [2, 2, 0, 0, 1],
       [2, 2, 1, 2, 1],
       [1, 0, 1, 0, 2]])

In [30]:
i,j = np.where(np_matrix == 2)

In [31]:
j

array([0, 2, 2, 4, 0, 1, 0, 1, 3, 4])

In [32]:
i

array([0, 0, 1, 1, 2, 2, 3, 3, 3, 4])

In [33]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 8,  1,  5,  7,  0],
       [ 9, 10,  1,  5,  9],
       [ 2,  0, 10,  0,  4],
       [ 6,  3,  1,  8,  5],
       [ 9,  5,  4,  2,  7]])

In [34]:
i,j = np.where(np_matrix == 1)

In [35]:
i

array([0, 1, 3])

In [36]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[8, 1, 5, 7, 0],
       [6, 3, 1, 8, 5],
       [9, 5, 4, 2, 7]])

In [37]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 8,  7,  3, 10,  4],
       [ 8,  6,  3,  8,  8],
       [ 5,  1,  3,  3,  3],
       [ 2,  6,  5,  5,  2],
       [ 5,  6,  1,  5,  0]])

In [38]:
np_matrix = np.delete(np_matrix,[1,2],1)
np_matrix

array([[ 8, 10,  4],
       [ 8,  8,  8],
       [ 5,  3,  3],
       [ 2,  5,  2],
       [ 5,  5,  0]])

In [39]:
np.arange(0,25,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [40]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[5, 1, 3, 4, 2],
       [5, 3, 1, 2, 1],
       [2, 3, 5, 5, 3],
       [1, 1, 4, 2, 2],
       [2, 5, 2, 1, 4]])

In [41]:
np.max(data)

5

In [42]:
np.max(data,0)

array([5, 5, 5, 5, 4])

In [43]:
np.max(data,1)


array([5, 5, 5, 4, 5])

#assignment 2 

In [44]:
np_mat = np.random.rand(10,5)
np_A1 = np.round(np_mat[:,4])
np_mat[:,4] = np_A1
np_mat


array([[0.99198426, 0.43552082, 0.36242738, 0.87312734, 0.        ],
       [0.74386203, 0.75418095, 0.3236832 , 0.73535139, 0.        ],
       [0.13209176, 0.00997191, 0.37304105, 0.01080092, 1.        ],
       [0.24316678, 0.68002726, 0.67713974, 0.88582741, 0.        ],
       [0.94669413, 0.29374373, 0.73660054, 0.47553897, 0.        ],
       [0.82745335, 0.5396978 , 0.35417242, 0.84199769, 0.        ],
       [0.06773524, 0.62818122, 0.63494351, 0.76973697, 0.        ],
       [0.85846834, 0.38166258, 0.96478065, 0.78030187, 0.        ],
       [0.34609815, 0.53918262, 0.43121391, 0.78263302, 1.        ],
       [0.69261888, 0.3438399 , 0.575779  , 0.41890731, 0.        ]])

#assignment 3

In [45]:
idx = [1,2,3,4]
np_matrix[idx,:]

array([[8, 8, 8],
       [5, 3, 3],
       [2, 5, 2],
       [5, 5, 0]])

#assignment 4 

In [55]:
np_matrix = np.random.randint(10,size = (10,5))
label_vector = np.random.randint(2,size = (10,))

In [53]:
np_matrix


array([[1, 6, 2, 1, 3],
       [6, 3, 9, 0, 4],
       [2, 7, 5, 5, 3],
       [9, 1, 8, 1, 4],
       [6, 2, 6, 7, 5],
       [0, 1, 5, 6, 9],
       [8, 8, 2, 6, 0],
       [6, 0, 4, 3, 3],
       [7, 0, 9, 2, 2],
       [3, 5, 6, 0, 6]])

In [56]:
label_vector

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1])

In [57]:
train_data = (label_vector == 0)
np_matrix[train_data]

array([[5, 7, 5, 7, 4],
       [1, 0, 6, 7, 7],
       [8, 4, 9, 2, 7],
       [0, 6, 1, 8, 5],
       [1, 0, 5, 0, 9]])

In [58]:
test_data = (label_vector == 1)
np_matrix[test_data]

array([[5, 9, 3, 6, 4],
       [8, 2, 6, 9, 9],
       [8, 2, 4, 1, 1],
       [2, 2, 6, 7, 9],
       [8, 3, 9, 4, 8]])

#assignment 5

In [46]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[3, 5, 4, 3, 5],
       [5, 3, 4, 3, 5],
       [3, 3, 4, 3, 4],
       [4, 3, 4, 1, 5],
       [3, 4, 3, 2, 3]])

In [47]:
-np.sort(data[0,:]*-1)

array([5, 5, 4, 3, 3])

#assignment 6

In [50]:
np_test= np.arange(25).reshape(5,5)
ans = (np_test%3 == 0)
np_test[ans]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

#assignment 7

In [51]:
np_test[(np.eye(5) == 1)] = 0
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16, 17,  0, 19],
       [20, 21, 22, 23,  0]])